language: python

python:
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - pushd deploy
  - ./install_taxbrain_server.sh
  - popd
  - source activate aei_dropq

before_script:
  - python manage.py syncdb --noinput
  - python manage.py makemigrations taxbrain
  - python manage.py migrate taxbrain
  - python manage.py migrate --fake

script:
  - py.test webapp/apps/ -m "not requires_pufcsv"
